# Generated by Django 2.2.12 on 2020-05-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.PositiveIntegerField(unique=True, verbose_name='ClickUp ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
            ],
        ),
        migrations.AddField(
            model_name='cfolder',
            name='c_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.CSpace'),
        ),
        migrations.AddField(
            model_name='clist',
            name='c_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='core.CFolder'),
        ),
        migrations.AddField(
            model_name='ctask',
            name='c_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.CList'),
        ),
        migrations.AlterField(
            model_name='cfolder',
            name='name',
            field=models.TextField(max_length=2048, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='clist',
            name='name',
            field=models.TextField(max_length=2048, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cspace',
            name='name',
            field=models.TextField(max_length=2048, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ctask',
            name='name',
            field=models.TextField(max_length=2048, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='cspace',
            name='c_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='core.CTeam'),
        ),
    ]
