# Generated by Django 2.2.12 on 2020-05-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ctask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfolder',
            options={'verbose_name': 'ClickUp Folder', 'verbose_name_plural': 'ClickUp Folders'},
        ),
        migrations.AlterModelOptions(
            name='clist',
            options={'verbose_name': 'ClickUp List', 'verbose_name_plural': 'ClickUp Lists'},
        ),
        migrations.AlterModelOptions(
            name='cspace',
            options={'verbose_name': 'ClickUp Space', 'verbose_name_plural': 'ClickUp Spaces'},
        ),
        migrations.AlterModelOptions(
            name='ctask',
            options={'verbose_name': 'ClickUp Task', 'verbose_name_plural': 'ClickUp Tasks'},
        ),
        migrations.AlterModelOptions(
            name='cteam',
            options={'verbose_name': 'ClickUp Team', 'verbose_name_plural': 'ClickUp Teams'},
        ),
    ]
