# Generated by Django 2.2.12 on 2020-05-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200513_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfolder',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cfolder',
            name='name',
            field=models.TextField(max_length=2048, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='clist',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='clist',
            name='name',
            field=models.TextField(max_length=2048, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cspace',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cspace',
            name='name',
            field=models.TextField(max_length=2048, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ctask',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ctask',
            name='name',
            field=models.TextField(max_length=2048, null=True, verbose_name='name'),
        ),
    ]
