# Generated by Django 2.2.12 on 2020-05-14 13:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200513_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=50, unique=True, verbose_name='ClickUp ID')),
                ('c_json_res', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='ClickUp JSON Response')),
                ('c_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.CTeam')),
            ],
        ),
    ]
