# Generated by Django 2.2.12 on 2020-05-16 02:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200514_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctask',
            name='c_id',
            field=models.CharField(editable=False, max_length=12, unique=True, verbose_name='ClickUp ID'),
        ),
        migrations.AlterField(
            model_name='ctask',
            name='c_json_res',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='TaskCreated JSON Response'),
        ),
        migrations.AlterField(
            model_name='ctask',
            name='c_list',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.CList'),
        ),
        migrations.AlterField(
            model_name='ctask',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
