# Generated by Django 2.2.12 on 2020-05-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200516_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfolder',
            old_name='c_id',
            new_name='clickup_id',
        ),
        migrations.RenameField(
            model_name='clist',
            old_name='c_id',
            new_name='clickup_id',
        ),
        migrations.RenameField(
            model_name='cspace',
            old_name='c_id',
            new_name='clickup_id',
        ),
        migrations.RenameField(
            model_name='cspace',
            old_name='c_team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='ctask',
            old_name='c_id',
            new_name='clickup_id',
        ),
        migrations.RenameField(
            model_name='cteam',
            old_name='c_id',
            new_name='clickup_id',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='c_id',
            new_name='clickup_id',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='c_team',
            new_name='team',
        ),
    ]
