# Generated by Django 2.2.12 on 2020-05-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200516_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='c_space',
            new_name='space',
        ),
    ]
