# Generated by Django 2.2.12 on 2020-05-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200516_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='c_folder',
            new_name='folder',
        ),
    ]
