# Generated by Django 2.2.12 on 2020-05-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200516_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='c_list',
            new_name='_list',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='c_json_res',
            new_name='created_json',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='c_update_json_res',
            new_name='updated_json',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='c_json_res',
            new_name='created_json',
        ),
    ]
