# Generated by Django 2.2.12 on 2020-05-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.PositiveIntegerField(unique=True, verbose_name='ClickUp ID')),
                ('is_active', models.BooleanField(verbose_name='is active?')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.PositiveIntegerField(unique=True, verbose_name='ClickUp ID')),
                ('is_active', models.BooleanField(verbose_name='is active?')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.PositiveIntegerField(unique=True, verbose_name='ClickUp ID')),
                ('is_active', models.BooleanField(verbose_name='is active?')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='is active?')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('c_id', models.CharField(max_length=12, unique=True, verbose_name='ClickUp ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
