# Generated by Django 2.2.12 on 2020-05-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200513_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfolder',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='is active?'),
        ),
        migrations.AlterField(
            model_name='clist',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='is active?'),
        ),
        migrations.AlterField(
            model_name='cspace',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='is active?'),
        ),
        migrations.AlterField(
            model_name='ctask',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='is active?'),
        ),
    ]
