# Generated by Django 2.2.12 on 2020-05-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200513_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfolder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='clist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cspace',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ctask',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
