# Generated by Django 2.2.12 on 2020-05-13 21:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20200513_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctask',
            name='c_json_res',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='ClickUp JSON Response'),
        ),
        migrations.AddField(
            model_name='ctask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
