# Generated by Django 2.2.12 on 2020-05-14 14:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctask',
            name='c_update_json_res',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='TaskUpdated JSON Response'),
        ),
    ]
