# Generated by Django 2.2.12 on 2020-06-01 01:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_team_is_imported'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickup_id', models.CharField(max_length=40, verbose_name='ClickUp ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('_type', models.CharField(max_length=20)),
                ('type_config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='ClickUp JSON Response')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='custom_fields_imported',
            field=models.BooleanField(default=False, verbose_name='Custom fields imported?'),
        ),
        migrations.CreateModel(
            name='TaskCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_custom_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_custom_fields', to='core.ListCustomField')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='core.Task')),
            ],
        ),
        migrations.AddField(
            model_name='listcustomfield',
            name='_list',
            field=models.ManyToManyField(related_name='custom_fields', to='core.List'),
        ),
    ]
