# Generated by Django 2.2.12 on 2020-05-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200516_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CTeam',
            new_name='Team',
        ),
    ]
