# Generated by Django 2.2.12 on 2020-06-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200601_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listcustomfield',
            old_name='_list',
            new_name='lists',
        ),
    ]
