# Generated by Django 2.2.12 on 2020-05-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200516_0309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSpace',
            new_name='Space',
        ),
    ]
