# Generated by Django 2.2.12 on 2020-05-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200516_0311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CFolder',
            new_name='Folder',
        ),
    ]
