# Generated by Django 2.2.12 on 2020-06-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200601_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcustomfield',
            name='clickup_id',
            field=models.CharField(max_length=40, unique=True, verbose_name='ClickUp ID'),
        ),
        migrations.AlterField(
            model_name='taskcustomfield',
            name='list_custom_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_custom_fields', to='core.ListCustomField'),
        ),
    ]
