# Generated by Django 2.2.12 on 2020-05-16 03:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20200516_0312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CTask',
            new_name='Task',
        ),
    ]
