# Generated by Django 2.2.12 on 2020-05-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200516_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
