# Generated by Django 2.2.12 on 2020-05-16 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200516_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.List'),
        ),
        migrations.AlterField(
            model_name='task',
            name='clickup_id',
            field=models.CharField(max_length=12, unique=True, verbose_name='ClickUp ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
